### PR TITLE
Ember 3.4 compatibility

### LINKED ISSUE #4: Ember 3.4 compatibility
Using 0.0.3 results in the following error (browser console):
`Uncaught Error: Could not find module `ember` imported from `ember-cli-lunr/services/lunr`
Also the cli complains about babel deprecation. This should be updated to at least 6.6, too.

### PR DESCRIPTION
**Pull request by jkubaile**
Updated Addon to ember 3.4 incl linting, codemods, fixed tests and removed bower dependencies. Fixes #4

### CODE REVIEW

**Comment by Charizard** [comment]
@jkubaile Thanks for contributing to the project. Can you add the newest ember versions to `.travis.yml` as well?

**Comment by Charizard** [comment]
@jkubaile Sorry, didn't see that you already did. Looks good.

**Comment by Charizard** [comment]
@jkubaile Released `0.0.4`. Enjoy the new version!!

**Comment by jkubaile** [comment]
Great news! Thank you very much!

**Pull request merged**
